name: Deploy itowns-cityFab-XR to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      # - run: npm install
      # If a build step is required (check if there's a build script in package.json), uncomment the next lines:
      - run: npm run build
      - uses: actions/upload-pages-artifact@v3
        with:
          # Change './' to './dist' or './build' if your app outputs to another folder
          path: './dist'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
